---
ignore:
  - ".github/*"
  - "roles/*"
rules:
  line-length:
    max: 180
    allow-non-breakable-words: true
    level: warning
  brackets:
    level: warning
    max-spaces-inside: 2
  braces:
    level: warning
    max-spaces-inside: 2
  colons:
    level: warning
  document-start:
    level: warning
  indentation:
    level: warning
  truthy:
    level: warning
