---
downloads: ~/.ansible-downloads/

ohmyzsh: false
powerlevel10k: false

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - fwartner/tap

homebrew_installed_packages: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []

# you need to add your AppStore / iCloud login info in a custom config.yml
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.

# Node packages
npm_yarn_packages: []

# Python packages
pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
