---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

dotfiles_repo: https://github.com/simonphumin/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dev/github/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx

homebrew_installed_packages:
  - aom
  - cloudflared
  - composer
  - ctop
  - curl
  - cyberduck
  - exiftool
  - flyctl
  - fontconfig
  - hcloud
  - htop
  - httpd
  - macos-term-size
  - mkcert
  - mono
  - n
  - python@3.11
  - git
  - libevent
  - sqlite
  - node
  - php
  - screenresolution
  - snappy
  - openssl
  - yarn
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - podman
  - dropbox
  - firefox
  - google-chrome
  - visual-studio-code
  - postman
  - adobe-creative-cloud
  - figma
  - sketch
  - keepassxc
  - slack
  - webex
  - warp
  - iterm2
  - imageoptim
  - vlc
  - keka
  - karabiner-elements
  - fontforge
  - rectangle-pro
  - onyx
  - miro
  - qlmarkdown
  - packages

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 1206020918, name: "Battery Indicator" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.

# Node packages
npm_yarn_packages:
  # - name: "@angular/cli"
  #   state: present # present/absent/latest, default: present
  #   version: "^15.2" # default: N/A
  - { name: "n", state: latest }
  - { name: "@angular/cli", state: present, version: "^15.2" }
  - name: serverless
    state: latest
  - name: npm-check-updates
    state: latest
  - name: pa11y
    state: latest
  - name: vercel
    state: latest
  - name: vsce
    state: latest
  - name: yo
    state: latest

# Python packages
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
