---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
    # role to install oh-my-zsh
  - name: gantsign.oh-my-zsh
    # role to install the powerlevel10k oh-my-zsh theme
  - name: diodonfrost.p10k

collections:
  - name: geerlingguy.mac
  # needed to configure npm packages with yarn
  - name: community.general
